mysite/enquetes/urls.py
from . import views
from django.urls import path

app_name='enquetes'
urlpatterns =[
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('<int:pk>/resultado/', views.ResultadoView.as_view(), name='resultado'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('raiz.urls')),
    path('enquetes/', include("enquetes.urls")),
]

mysite/raiz/urls.py
from django.urls import path
from .views import IndexView

app_name = 'raiz'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Pergunta(models.Model):
    texto = models.CharField(max_length=150)
    data_pub = models.DateTimeField("Data de publicação")
    def __str__(self):
        return f"{self.texto}({self.id})"
    def publicada_recente(self):
        agora = timezone.now()
        return self.data_pub >= agora - datetime.timedelta(hours = 24)

class Alternativa(models.Model):
    texto = models.CharField(max_length=100)
    quant_votos = models.IntegerField("Quantidade de votos", default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return "{}({})".format(self.texto, self.id)

mysite/raiz/models.py
from django.db import models

# Create your models here.

mysite/enquetes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Pergunta, Alternativa
from django.urls import reverse
from django.views import View

# Create your views here


class IndexView(View):
    def get(self, request, *args, **kwargs):
        enquetes = Pergunta.objects.order_by('-data_pub')[:10]
        contexto = {'lista_enquetes': enquetes}
        return render(request, 'enquetes/index.html', contexto)


class DetalhesView(View):
    template = 'enquetes/pergunta_detail.html'

    def resposta(self, request, pergunta, error):
        if error:
            contexto = {'enquete': pergunta, 'error': error}
        else:
            contexto = {'enquete': pergunta}
        return render(request, self.template, contexto)

    def get(self, request, *args, **kwargs):
        pergunta_id = kwargs['pk']
        pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
        return self.resposta(request, pergunta, None)

    def post(self, request, *args, **kwargs):
        pergunta_id = kwargs['pk']
        pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
        try:
            id_alternativa = request.POST['escolha']
            alt = pergunta.alternativa_set.get(pk=id_alternativa)
        except (KeyError, Alternativa.DoesNotExist):
            error = 'Você precisa selecionar uma alternativa.'
            return self.resposta(request, pergunta, error)
        else:
            alt.quant_votos += 1
            alt.save()
            return HttpResponseRedirect(reverse('enquetes:resultado', args=(pergunta.id,)))


class ResultadoView(View):
    def get(self, request, *args, **kwargs):
        pergunta_id = kwargs['pk']
        pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
        contexto = {'enquete': pergunta}
        return render(request, 'enquetes/resultado.html', contexto)


"""
Poderia ter feito assim, bem mais fácil...
from django.shortcuts import get_object_or_404, render
def detalhes(request, pergunta_id):
    questao = get_object_or_404(Pergunta, pk= pergunta_id)
    return render(request, 'enquetes/detalhes.html', {'questao': questao})


def index(request):
    lista = Pergunta.objects.all()
    template = loader.get_template('enquetes/index.html')
    contexto = {'lista_enquetes': lista}
    return HttpResponse(template.render(contexto, request))


def resultado(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk= pergunta_id)
    return render(request, 'enquetes/resultado.html', {'enquete': pergunta})#esse resto aqui é o contexto


def detalhes(request, pergunta_id):
    try:
         pergunta = Pergunta.objects.get(pk = pergunta_id)
    except Pergunta.DoesNotExist:
         raise Http404('Identificação de enquete inválida!')
    return render(request, 'enquetes/detalhes.html', {'enquete': pergunta})


def votacao(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        id_alternativa = request.POST['escolha']
        alt = pergunta.alternativa_set.get(pk=id_alternativa)
    except (KeyError, Alternativa.DoesNotExist):
        contexto = {
            'enquete': pergunta,
            'error': 'Você precisa selecionar uma alternativa.'
        }
        return render(request, 'enquetes/detalhes.html', contexto)
    else:
        alt.quant_votos += 1
        alt.save()
        return HttpResponseRedirect(reverse('enquetes:resultado', args=(pergunta.id,)))
"""

mysite/raiz/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "raiz/index.html")


# def index(request):
#     return render(request, 'raiz/index.html')

mysite/enquetes/templates/enquetes/index.html
<!--<html>-->
<!--    <head>-->
<!--        <title>App Enquetes</title>-->
<!--    </head>-->
<!--    <body>-->
<!--        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>-->
<!--        {% if lista_enquetes %}-->
<!--            <h3>Lista das Enquetes Cadastradas:</h3>-->
<!--            <ul>-->
<!--                {% for p in lista_enquetes %}-->
<!--                    <li>-->
<!--                        <a href="/enquetes/{{ p.id }}"Linha 34!!!!!! aqui a url é estática, no modo abaixo ele fica dinâmico e não precisa ficar alterando em muitos lugares, somente no urlpatters>-->
<!--                            {{ p.texto }}-->
<!--                        </a>-->
<!--                    </li>-->
<!--                {% endfor %}-->
<!--            </ul>-->
<!--        {% else %}-->
<!--            <h3>Nenhuma enquete cadastrada até o momento!</h3>-->
<!--        {% endif %}-->
<!--    </body>-->
<!--</html>-->
{% load static %}
<html>
    <head>
        <title>App Enquetes</title>
        <link rel="stylesheet" type="text/css" href="{% static 'enquetes/css/style.css' %}" >
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        {% if lista_enquetes %}
            <h3>Lista das Enquetes Cadastradas:</h3>
            <ul>
                {% for p in lista_enquetes %}
                    <li>
                        <a href="{% url 'enquetes:detalhes' p.id %}">
                            {{ p.texto }}
                        </a>&nbsp;&nbsp;
                        (<a href="{% url 'enquetes:resultado' p.id %}">
                            ver PARCIAL
                        </a>)
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Nenhuma enquete cadastrada até o momento!</h3>
        {% endif %}
        <hr>
        <a href="{% url 'raiz:index' %}">
        &copy; DSWeb/TADS/CNAT/IFRN - 2024.
        </a>
    </body>
</html>

mysite/enquetes/templates/enquetes/pergunta_detail.html
{% load static %}
<html>
    <head>
        <title>App Enquetes</title>
        <link rel='stylesheet' type='text/css' href='{% static 'enquetes/css/style.css' %}'>
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>Enquete #{{ enquete.id }}</h2>
        <h2>{{ enquete.texto }}</h2>
        <p><i>{{ enquete.data_pub }}</i></p>
        {% if error %}
            <dt><b>Erro: {{ error }}</b></dt>
        {% endif %}
        <p>Selecione a alternativa desejada:</p>
        <form action="{% url 'enquetes:detalhes' enquete.id %}" method="post">
            {% csrf_token %}
            <ul>
            {% for alt in enquete.alternativa_set.all %}
                <li>
                    <input type="radio" name="escolha" value="{{ alt.id }}" id="alt{{ forloop.counter }}"/>
                    <label for="alt{{ forloop.counter }}">
                        {{ alt.texto }}
                    </label>
                </li>
            {% endfor %}
            </ul>
            <input type="submit" value="Registre o seu voto"/>
        </form>
        <hr>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
    </body>
</html>

mysite/enquetes/templates/enquetes/resultado.html
{% load static %}
<html>
    <head>
        <link rel='stylesheet' type='text/css' href='{% static 'enquetes/css/style.css' %}'>
        <title>App Enquetes</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>PARCIAL da Enquete #{{ enquete.id }}</h2>
        <h2>{{ enquete.texto }}</h2>
        <p><i>{{ enquete.data_pub }}</i></p>
        <p>Quantidade de votos por alternativas:</p>
        <ul>
            {% for alt in enquete.alternativa_set.all %}
                <li>
                    {{ alt.texto }} == {{ alt.quant_votos }}
                    voto{{ alt.quant_votos | pluralize }}
                </li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{% url 'enquetes:detalhes' enquete.id %}">Votar novamente?</a>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
    </body>
</html>

mysite/raiz/templates/raiz/index.html
{% load static %}
<html>
    <head>
        <link rel='stylesheet' type='text/css' href='{% static 'enquetes/css/style.css' %}'>
        <title>DSWeb 2024.1</title>
    </head>
    <body>
        <h1>Disciplina DSWeb 2024.1</h1>
        <h3>Aplicações criadas</h3>
        <hr>
        <ol>
            <li><a href="/enquetes/">
                Aplicação de Enquetes
            </a></li>
        </ol>
        <hr>
        &copy; DSWeb/TADS/CNAT/IFRN - 2024.
    </body>
</html>